import idlJson from "../idl/cortex_program.json";
import type { CortexProgram } from "../idl/cortex_program";

// The IDL JSON is generated by `anchor build` and copied into
// `sdk/idl/` (run `npm run sync-idl` to refresh). Re-exporting the
// typed reference plus the raw shape so consumers don't have to know
// the path.
export const cortexProgramIdl = idlJson as unknown as CortexProgram;

export type { CortexProgram } from "../idl/cortex_program";

export const CORTEX_PROGRAM_ID = "DBUXLUHZk8UEGJgdbAAaazTuLoCKbReDF1tNPa5fMprV";
